package no.ssb.klass.designer;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.Button;
import com.vaadin.ui.Label;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.declarative.Design;
import no.ssb.klass.designer.classificationlist.ClassificationTable;
import no.ssb.klass.designer.classificationlist.VariantTable;
import no.ssb.klass.designer.classificationlist.VersionTable;

/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class ClassificationListDesign extends VerticalLayout {
    protected Button backButton;
    protected Label familyLabel;
    protected ClassificationTable classificationTable;
    protected VersionTable versionTable;
    protected VariantTable variantTable;

    public ClassificationListDesign() {
        Design.read(this);
    }
}
