package no.ssb.klass.designer;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.Button;
import com.vaadin.ui.CheckBox;
import com.vaadin.ui.PasswordField;
import com.vaadin.ui.TextArea;
import com.vaadin.ui.TextField;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.declarative.Design;

/**
 * !! DO NOT EDIT THIS FILE !!
 * <p/>
 * This class is generated by Vaadin Designer and will be overwritten.
 * <p/>
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { … }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class LoginDesign extends VerticalLayout {
    protected TextField usernameTextField;
    protected PasswordField passwordTextField;
    protected CheckBox rememberMeCheckbox;
    protected Button loginButton;
    protected VerticalLayout testUserLayout;
    protected Button adminBtn;
    protected Button ziggyBtn;
    protected Button bowieBtn;
    protected TextArea debugText;

    public LoginDesign() {
        Design.read(this);
    }
}
