package no.ssb.klass.designer;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.Button;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.NativeSelect;
import com.vaadin.ui.Panel;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.declarative.Design;

import no.ssb.klass.designer.components.BreadcumbPanel;

/**
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed, e.g class LoginView extends LoginDesign
 * implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class MainDesign extends VerticalLayout {
    protected HorizontalLayout topPanel;
    protected Button klassLogo;
    protected VerticalLayout userIcon;
    protected HorizontalLayout filterPanel;
    protected NativeSelect selectKodeverk;
    protected NativeSelect selectSection;
    protected BreadcumbPanel breadcrumbPanel;
    protected Panel content;

    public MainDesign() {
        Design.read(this);
    }
}
