package no.ssb.klass.designer.admin.tabs;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.Button;
import com.vaadin.ui.ComboBox;
import com.vaadin.ui.DateField;
import com.vaadin.ui.Grid;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.TextArea;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.declarative.Design;

/**
 * !! DO NOT EDIT THIS FILE !!
 * <p/>
 * This class is generated by Vaadin Designer and will be overwritten.
 * <p/>
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class LoggMessageTabDesign extends VerticalLayout {
    protected ComboBox classificationComboBox;
    protected ComboBox versionComboBox;
    protected Button newButton;
    protected Grid loggMessageGrid;
    protected HorizontalLayout hlayout;
    protected DateField dato;
    protected TextArea kommentarer;
    protected HorizontalLayout buttonhlayout;
    protected Button saveButton;
    protected Button cancelButton;

    public LoggMessageTabDesign() {
        Design.read(this);
    }
}
