package no.ssb.klass.designer.admin.tabs;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.declarative.Design;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.Button;
import com.vaadin.ui.Label;
import com.vaadin.ui.Table;
import com.vaadin.ui.HorizontalLayout;

/**
 * !! DO NOT EDIT THIS FILE !!
 * <p/>
 * This class is generated by Vaadin Designer and will be overwritten.
 * <p/>
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class SubscriberUnitTabDesign extends VerticalLayout {
    protected Table subscriberUnitTable;
    protected Button backButton;
    protected Label headingText;
    protected Label numberOfRowsHeader;
    protected VerticalLayout detailedSubscriberLayout;
    protected Table detailedSubscriberTable;
    protected HorizontalLayout pagingButtons;

    public SubscriberUnitTabDesign() {
        Design.read(this);
    }
}
