package no.ssb.klass.designer.components.common;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.Button;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.declarative.Design;

/**
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed, e.g class LoginView extends LoginDesign
 * implements View { … }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class ConfirmOrCancelDesign extends VerticalLayout {
    protected Button confirmButton;
    protected Button cancelButton;

    public ConfirmOrCancelDesign() {
        Design.read(this);
    }
}
