apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  title: Klass API Service
  name: klass-api-service
  description:
    Spring Boot application that handles classifications for SSB. Klass provides a REST api that clients can use to read classifications.
  tags:
    - on-prem
    - metadata
    - java
    - classification
    - codelist
  annotations:
    github.com/project-slug: statisticsnorway/klass
spec:
  type: service
  owner: dapla-metadata-developers
  lifecycle: production
  system: metadata
  providesApis:
    - klass-api
  dependsOn:
    - resource:klass-mariadb
    - component:ssbno-varnish
---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  title: Klass API
  name: klass-api
  description: REST api that clients can use to read classifications
  links:
    - url: https://data.ssb.no/api/klass/v1/api-guide.html
spec:
  type: openapi
  lifecycle: production
  owner: dapla-metadata-developers
  system: metadata
  definition:
    $text: .
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  title: Klass Forvaltning
  name: klass-forvaltning
  description:
    A Vaadin frontend for maintaining classifications for Klass.
  tags:
    - on-prem
    - metadata
    - java
    - vaadin
    - classification
    - codelist
  annotations:
    github.com/project-slug: statisticsnorway/klass
spec:
  type: website
  owner: dapla-metadata-developers
  lifecycle: production
  system: metadata
  dependsOn:
    - resource:klass-mariadb
---
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: klass-mariadb
  title: Klass MariaDB
  description: MariaDB database storing Klass data
  tags:
    - on-prem
    - database
spec:
  type: database
  system: metadata
  owner: dapla-metadata-developers
  lifecycle: production
