services:
  postgresql:
    image: postgres:17.4
    container_name: klass_postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: "klass"
      POSTGRES_DB: "klass"
