package no.ssb.klass.designer.editing.version;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.Accordion;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.declarative.Design;

import no.ssb.klass.designer.components.common.ConfirmOrCancelComponent;

/**
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed, e.g class LoginView extends LoginDesign
 * implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class VersionMainEditor extends VerticalLayout {
    protected Accordion versionAccordion;
    protected VersionEditorView metadataEditor;
    protected CodeEditorView codeEditor;
    protected ConfirmOrCancelComponent actionButtons;

    public VersionMainEditor() {
        Design.read(this);
    }
}
