package no.ssb.klass.designer.admin;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.TabSheet;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.declarative.Design;

/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class ContentUseStatDesign extends VerticalLayout {
    protected TabSheet contentStatTab;
    protected VerticalLayout codesPanel;
    protected VerticalLayout detailedReportHeading;
    protected VerticalLayout reportLayout;
    protected VerticalLayout usePanel;
    protected UseStatisticsView useStatisticsView;
    protected DetailedUseReportView useDetailedUseView;
    protected VerticalLayout staticalUnit;
    protected StatisticalUnitView statisticalUnitView;
    protected ClassificationUnitReportView classificationUnitReportView;

    public ContentUseStatDesign() {
        Design.read(this);
    }
}
