# Deploy config for the prod cluster
apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: klass
  namespace: dapla-metadata
  labels:
    team: dapla-metadata
spec:
  port: 8080
  ingresses:
    - https://klass.intern.ssb.no/api/klass
  replicas:
    min: 2
    max: 2
  resources:
    requests:
      cpu: 155m
      memory: 2500Mi
    limits:
      memory: 2500Mi
  gcp:
    sqlInstances:
      - type: POSTGRES_17
        tier: db-custom-4-7680
        databases:
          - name: klass
  env:
    - name: SPRING_PROFILES_ACTIVE
      value: api, postgres, remote-open-search, skip-indexing
    - name: OPENSEARCH_USERNAME
      value: ${OPEN_SEARCH_USERNAME}
    - name: OPENSEARCH_URL
      value: ${OPEN_SEARCH_URI}
    - name: OPENSEARCH_PASSWORD
      value: ${OPEN_SEARCH_PASSWORD}
      # Structured logging in cluster
    - name: LOGGING_STRUCTURED_FORMAT_CONSOLE
      value: logstash
    - name: KLASS_ENV_CLIENT_KLASS_MAIL_URL
      value: http://klass-mail
    - name: JAVA_TOOL_OPTIONS
      value: "-XX:+ExitOnOutOfMemoryError -XX:InitialRAMPercentage=75.0 -XX:MaxRAMPercentage=75.0"

  accessPolicy:
    outbound:
      rules:
        - application: klass-mail
    inbound:
      rules:
        - application: dataportalen
  openSearch:
    access: admin
    instance: klass-search

  prometheus:
    enabled: true
    path: /actuator/prometheus
    port: "8090"

  liveness:
    path: /actuator/health/liveness
    port: 8090
    initialDelay: 60
    timeout: 180
  readiness:
    path: /actuator/health/readiness
    port: 8090
    initialDelay: 60
    timeout: 180
  startup:
    path: /actuator/health/liveness
    port: 8090
    initialDelay: 60
    timeout: 180
