-- Create initial version of postgres database

CREATE TABLE classification_family
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY,
    deleted       BIT NOT NULL,
    last_modified TIMESTAMP NOT NULL,
    uuid          VARCHAR(255) NOT NULL,
    version       INTEGER NOT NULL,
    icon_name     VARCHAR(255) NOT NULL,
    name          VARCHAR(255) NOT NULL,
    PRIMARY KEY (id)
);