UPDATE classification_family SET name = '<no>Arbeid og lønn</no><nn>Arbeid og løn</nn><en>Labour market and earnings</en>' WHERE name = 'Arbeid og lønn'; 
UPDATE classification_family SET name = '<no>Bank og finansmarked</no><nn>Bank og finansmarknad</nn><en>Banking and financial markets</en>' WHERE name = 'Bank og finansmarked'; 
UPDATE classification_family SET name = '<no>Befolkning</no><nn>Befolkning</nn><en>Population</en>' WHERE name = 'Befolkning';
UPDATE classification_family SET name = '<no>Bygg, bolig og eiendom</no><nn>Bygg, bustad og eigedom</nn><en>Construction, housing and property</en>' WHERE name = 'Bygg, bolig og eiendom';
UPDATE classification_family SET name = '<no>Energi og industri</no><nn>Energi og industri</nn><en>Energy and manufacturing</en>' WHERE name = 'Energi og industri';
UPDATE classification_family SET name = '<no>Helse</no><nn>Helse</nn><en>Health</en>' WHERE name = 'Helse';
UPDATE classification_family SET name = '<no>Inntekt og forbruk</no><nn>Inntekt og forbruk</nn><en>Income and consumption</en>' WHERE name = 'Inntekt og forbruk'; 
UPDATE classification_family SET name = '<no>Innvandring og innvandrere</no><nn>Innvandring og innvandrarar</nn><en>Immigration and immigrants</en>' WHERE name = 'Innvandring og innvandrere'; 
UPDATE classification_family SET name = '<no>Internt SSB</no><nn>Internt SSB</nn><en>For internal use Statistics Norway</en>' WHERE name = 'Internt SSB';
UPDATE classification_family SET name = '<no>Jord, skog, jakt og fiskeri</no><nn>Jord, skog, jakt og fiskeri</nn><en>Agriculture, forestry, hunting and fishing</en>' WHERE name = 'Jord, skog, jakt og fiskeri';
UPDATE classification_family SET name = '<no>Kultur og fritid</no><nn>Kultur og fritid</nn><en>Culture and recreation</en>' WHERE name = 'Kultur og fritid';
UPDATE classification_family SET name = '<no>Nasjonalregnskap og konjunkturer</no><nn>Nasjonalrekneskap og konjunkturar</nn><en>National accounts and business cycles</en>' WHERE name = 'Nasjonalregnskap og konjunkturer';
UPDATE classification_family SET name = '<no>Natur og miljø</no><nn>Natur og miljø</nn><en>Nature and environment</en>' WHERE name = 'Natur og miljø';
UPDATE classification_family SET name = '<no>Offentlig sektor</no><nn>Offentleg sektor</nn><en>Public sector</en>' WHERE name = 'Offentlig sektor';
UPDATE classification_family SET name = '<no>Priser og prisindekser</no><nn>Prisar og prisindeksar</nn><en>Prices and price indices</en>' WHERE name = 'Priser og prisindekser';
UPDATE classification_family SET name = '<no>Region</no><nn>Region</nn><en>Region</en>' WHERE name = 'Region';
UPDATE classification_family SET name = '<no>Sosiale forhold og kriminalitet</no><nn>Sosiale forhold og kriminalitet</nn><en>Social conditions welfare and crime</en>' WHERE name = 'Sosiale forhold og kriminalitet';
UPDATE classification_family SET name = '<no>Svalbard</no><nn>Svalbard</nn><en>Svalbard</en>' WHERE name = 'Svalbard';
UPDATE classification_family SET name = '<no>Teknologi og innovasjon</no><nn>Teknologi og innovasjon</nn><en>Technology and innovation</en>' WHERE name = 'Teknologi og innovasjon';
UPDATE classification_family SET name = '<no>Transport og reiseliv</no><nn>Transport og reiseliv</nn><en>Transport and tourism</en>' WHERE name = 'Transport og reiseliv';
UPDATE classification_family SET name = '<no>Utdanning</no><nn>Utdanning</nn><en>Education</en>' WHERE name = 'Utdanning';
UPDATE classification_family SET name = '<no>Utenriksøkonomi</no><nn>Utanriksøkonomi</nn><en>External economy</en>' WHERE name = 'Utenriksøkonomi';
UPDATE classification_family SET name = '<no>Valg</no><nn>Val</nn><en>Elections</en>' WHERE name = 'Valg';
UPDATE classification_family SET name = '<no>Varehandel og tjenesteyting</no><nn>Varehandel og tenesteyting</nn><en>Wholesale and retail trade and service activities</en>' WHERE name = 'Varehandel og tjenesteyting';
UPDATE classification_family SET name = '<no>Virksomheter, foretak og regnskap</no><nn>Verksemder, føretak og rekneskap</nn><en>Establishments, enterprises and accounts</en>' WHERE name = 'Virksomheter, foretak og regnskap';
