package no.ssb.klass.designer.windows;

import no.ssb.klass.designer.components.common.ConfirmOrCancelComponent;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.ComboBox;
import com.vaadin.ui.Label;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.declarative.Design;

/**
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed, e.g class LoginView extends LoginDesign
 * implements View { … }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class NewCorrespondenceTableWindowDesign extends VerticalLayout {
    protected Label headerLabel;
    protected Label fromCorrespondenceLabel;
    protected ComboBox toClassificationCombobox;
    protected ComboBox toVersionCombobox;
    protected ComboBox fromLevelCombobox;
    protected ComboBox toLevelCombobox;
    protected ConfirmOrCancelComponent actionButtons;

    public NewCorrespondenceTableWindowDesign() {
        Design.read(this);
    }
}
