package no.ssb.klass.designer.editing.variant;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.Button;
import com.vaadin.ui.Label;
import com.vaadin.ui.OptionGroup;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.declarative.Design;

import no.ssb.klass.designer.editing.codetables.MarkedTranslationCodeTableFilterWrapper;
import no.ssb.klass.designer.editing.codetables.ReadOnlyCodeTableFilterWrapper;
import no.ssb.klass.designer.editing.codetables.VariantCodeTableFilterWrapper;
import no.ssb.klass.designer.editing.codetables.levels.PrimaryLevelsComponent;
import no.ssb.klass.designer.editing.codetables.levels.ReadonlyLevelsComponent;
import no.ssb.klass.designer.editing.codetables.levels.TranslationLevelsComponent;
import no.ssb.klass.designer.editing.components.SelectEditLanguageOrVariantComponent;

/**
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed, e.g class LoginView extends LoginDesign
 * implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class VariantCodeEditorDesign extends VerticalLayout {
    protected OptionGroup dragAndDropMode;
    protected Button importButton;
    protected Button exportButton;
    protected Label primaryLanguage;
    protected SelectEditLanguageOrVariantComponent selectEditLanguageOrVariant;
    protected Label variantName;
    protected Label originalVersionName;
    protected PrimaryLevelsComponent variantLevels;
    protected TranslationLevelsComponent translatableLevels;
    protected ReadonlyLevelsComponent versionLevels;
    protected VariantCodeTableFilterWrapper variantCodeTable;
    protected ReadOnlyCodeTableFilterWrapper originalVersion;
    protected MarkedTranslationCodeTableFilterWrapper translationCodeTable;

    public VariantCodeEditorDesign() {
        Design.read(this);
    }
}
