package no.ssb.klass.designer.editing.correspondencetable;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.Button;
import com.vaadin.ui.Label;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.declarative.Design;

import no.ssb.klass.designer.editing.codetables.SourceCorrespondenceTableFilterWrapper;
import no.ssb.klass.designer.editing.codetables.TargetCorrespondenceTableFilterWrapper;

/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class CorrespondenceTableCodeEditorDesign extends VerticalLayout {
    protected Button importButton;
    protected Button exportButton;
    protected Label sourceVersionName;
    protected Label targetVersionName;
    protected SourceCorrespondenceTableFilterWrapper sourceVersion;
    protected TargetCorrespondenceTableFilterWrapper targetVersion;

    public CorrespondenceTableCodeEditorDesign() {
        Design.read(this);
    }
}
