# Deploy config for the test cluster
apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: klass-solr-pr
  namespace: dapla-metadata
  labels:
    team: dapla-metadata
  annotations:
    nais.io/read-only-file-system: "false"
    nais.io/run-as-user: "8983"
    nais.io/run-as-group: "8983"
spec:
  port: 8983

  filesFrom:
    - persistentVolumeClaim: klass-solr-pvc
      mountPath: /opt/solr/server/solr/mycores/Klass/data
  env:
    # Solr crashed with JAVA_TOOL_OPTIONS ref: https://github.com/apache/lucene-solr/pull/405
    # so we use this variable ref: https://solr.apache.org/guide/6_6/taking-solr-to-production.html#TakingSolrtoProduction-MemoryandGCSettings
    # Solr sets -Xmx512m by default so we MUST override this setting, otherwise the heap allocation will remain constrained
    # Value should be 50% of memory request
    - name: SOLR_JAVA_MEM
      value: "-Xms1g -Xmx1g"

  replicas:
    min: 1
    max: 1
  resources:
    requests:
      cpu: 100m
      # Update SOLR_JAVA_MEM when changing this
      memory: 2Gi
    limits:
      memory: 2Gi

  accessPolicy:
    inbound:
      rules:
        - application: klass-pr
        - application: klass-forvaltning


  liveness:
    path: /solr/admin/cores?action=STATUS
    port: 8983
    initialDelay: 60

  readiness:
    path: /solr/admin/cores?action=STATUS
    port: 8983
    initialDelay: 60

  startup:
    path: /solr/admin/cores?action=STATUS
    port: 8983
    initialDelay: 60
