services:
  klass-forvaltning:
    build:
      context: ../klass-forvaltning
      dockerfile: ../klass-forvaltning/Dockerfile
    container_name: klass-forvaltning
    ports:
      - "8081:8081"
    environment:
      SPRING_PROFILES_ACTIVE: frontend, h2-inmemory, small-import, skip-indexing, embedded-solr