package no.ssb.klass.designer.editing.classification;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.Button;
import com.vaadin.ui.CheckBox;
import com.vaadin.ui.ComboBox;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.Label;
import com.vaadin.ui.TextArea;
import com.vaadin.ui.TextField;
import com.vaadin.ui.TwinColSelect;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.declarative.Design;

import no.ssb.klass.designer.components.common.ConfirmOrCancelComponent;

/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class ClassificationEditorDesign extends VerticalLayout {
    protected Label headerLabel;
    protected VerticalLayout bokmalLayout;
    protected Label primaryLabel;
    protected ComboBox classificationTypeCombobox;
    protected TextField primaryTitlePrefixTextfield;
    protected TextField primaryTitleTextfield;
    protected TextArea primaryDescriptionTextArea;
    protected ComboBox familiesCombobox;
    protected ComboBox contactPersonCombobox;
    protected TextField sectionTextfield;
    protected TwinColSelect statisticalUnitSelector;
    protected ComboBox primaryLanguageCombobox;
    protected CheckBox includeShortnameCheckbox;
    protected CheckBox includeNotesCheckbox;
    protected CheckBox includeValidCheckbox;
    protected CheckBox copyrightCheckbox;
    protected VerticalLayout padding;
    protected VerticalLayout optional;
    protected VerticalLayout otherLanguages;
    protected HorizontalLayout languagesHeader;
    protected HorizontalLayout languageLayout;
    protected Button secondaryLanguageButton;
    protected Button thirdLanguageButton;
    protected Button languageToggleButton;
    protected HorizontalLayout secondaryLanguageLayout;
    protected VerticalLayout spacer;
    protected TextField secondaryTitlePrefixTextfield;
    protected TextField secondaryTitleTextfield;
    protected TextArea secondaryDescriptionTextArea;
    protected HorizontalLayout thirdLanguageLayout;
    protected VerticalLayout spacer2;
    protected TextField thirdTitlePrefixTextfield;
    protected TextField thirdTitleTextfield;
    protected TextArea thirdDescriptionTextArea;
    protected ConfirmOrCancelComponent actionButtons;

    public ClassificationEditorDesign() {
        Design.read(this);
    }
}
