name: Klass-api build and deploy

on:
  release:
    types: [ published ]
  push:
    branches:
      - nais-migration
    paths:
      - "klass-api/**"
      - "klass-shared/**"
      - ".nais/**/klass-api.yaml"
      - ".github/workflows/klass-api-build-and-deploy.yaml"

jobs:
  docker-build:
    name: Docker build
    permissions:
      contents: "read"
      id-token: "write"
      packages: "read"
    runs-on: ubuntu-latest
    outputs:
      nais_config_path: ${{ steps.nais-deploy-vars.outputs.nais_config_path }}
      nais_cluster: ${{ steps.nais-deploy-vars.outputs.nais_cluster }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'

      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots install -pl '!:klass-forvaltning'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: nais/docker-build-push@v0
        id: docker-build-push
        with:
          team: dapla-metadata
          image_suffix: api
          dockerfile: klass-api/Dockerfile
          docker_context: klass-api

      - name: Generate NAIS deploy variables
        id: nais-deploy-vars
        run: |
          if [[ ${{ github.event_name }} == "release" ]]; then
            echo "nais_cluster=prod" >> "$GITHUB_OUTPUT"
            echo "nais_config_path=.nais/prod/klass-api.yaml" >> "$GITHUB_OUTPUT"
          else
            echo "nais_cluster=test" >> "$GITHUB_OUTPUT"
            echo "nais_config_path=.nais/test/klass-api.yaml" >> "$GITHUB_OUTPUT"
          fi

      - uses: nais/deploy/actions/deploy@v2
        env:
          CLUSTER: ${{ steps.nais-deploy-vars.outputs.nais_cluster }}
          RESOURCE: ${{ steps.nais-deploy-vars.outputs.nais_config_path }}
          VAR: image=${{ steps.docker-build-push.outputs.image }}
          DEPLOY_SERVER: deploy.ssb.cloud.nais.io:443
          WORKLOAD_IMAGE: ${{ steps.docker-build-push.outputs.image }}
          TELEMETRY: ${{ steps.docker-build-push.outputs.telemetry }}
