name: Release

on:
  pull_request:
    types:
      - closed

jobs:
  release:
    runs-on: ubuntu-latest
    # Only run when a PR is merged from 'release' to 'main'
    if: github.event.pull_request.merged == true && github.event.pull_request.head.ref == 'release' && github.event.pull_request.base.ref == 'main'
    permissions:
      contents: write
      id-token: write
      packages: write

    steps:
      - name: Create DaplaBot app token
        uses: actions/create-github-app-token@fee1f7d63c2ff003460e3d139729b119787bc349 # v2.2.2
        id: app-token
        with:
          app-id: ${{ secrets.DAPLA_BOT_APP_ID }}
          private-key: ${{ secrets.DAPLA_BOT_PRIVATE_KEY }}

      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          token: ${{ steps.app-token.outputs.token }}
          ref: refs/heads/main

      - name: Set up JDK
        uses: actions/setup-java@ad2b38190b15e4d6bdf0c97fb4fca8412226d287 # v5.3.0
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: maven
          overwrite-settings: false

      - name: Get bot variables
        id: get-bot-vars
        run: |
          bot_name="dapla-bot"
          bot_id=$(curl -s https://api.github.com/users/${bot_name}%5Bbot%5D | jq '.id')
          bot_email="${dapla_bot_id}+${bot_name}[bot]@users.noreply.github.com"

          echo "bot_name=${bot_name}[bot]" >> $GITHUB_OUTPUT
          echo "bot_email=${bot_email}" >> $GITHUB_OUTPUT

      - name: Configure Git user
        run: |
          git config user.email ${{steps.get-bot-vars.outputs.bot_email}}
          git config user.name ${{steps.get-bot-vars.outputs.bot_name}}

      - name: Setup Maven authentication to GitHub packages
        uses: s4u/maven-settings-action@894661b3ddae382f1ae8edbeab60987e08cf0788 # v4.0.0
        with:
          override: true
          githubServer: false
          servers: >-
            [{"id": "github","username": "${{steps.get-bot-vars.outputs.bot_email}}","password": "${{steps.app-token.outputs.token}}",
            "configuration": {"httpHeaders": {"property": {"name": "Authorization","value": "Bearer ${{ secrets.GITHUB_TOKEN }}"}}}}]

      - name: Maven release
        id: release-artifact
        run: |
          # Prepare the release
          mvn --batch-mode release:prepare -DreleaseVersion=$(cat version.txt)
          # Perform the release
          mvn --batch-mode release:perform
          TAG=$(git describe --abbrev=0 --tags)
          echo "tag=${TAG}" >> $GITHUB_OUTPUT

      - name: Create GitHub release draft
        uses: release-drafter/release-drafter@6a93d829887aa2e0748befe2e808c66c0ec6e4c7 # v6.4.0
        id: create-github-release
        env:
          GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}
        with:
          tag: ${{ steps.release-artifact.outputs.tag }}

      - name: Publish GitHub release
        uses: eregon/publish-release@01df127f5e9a3c26935118e22e738d95b59d10ce # v1.0.6
        env:
          GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}
        with:
          release_id: ${{ steps.create-github-release.outputs.id }}
