name: Release
run-name: "Release to github packages"

on:
  release:
    types: [ created ]

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 1.8
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '8'
          cache: maven

      # Need to downgrade Maven in order to allow HTTP (not HTTPS) packages to be downloaded.
      # This is necessary as HTTP repositories were blocked in Maven 3.8.1
      # HTTP repositories are used in some outdated dependenciesns
      # This step can be removed once KLASS packages have been updated to more recent versions
      - name: Set up Maven
        uses: stCarolas/setup-maven@v4.5
        with:
          maven-version: 3.6.3

      - name: Publish to GitHub Packages
        run: mvn --batch-mode deploy -P github
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}