package no.ssb.klass.designer.components.metadata;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.CheckBox;
import com.vaadin.ui.ComboBox;
import com.vaadin.ui.DateField;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.Label;
import com.vaadin.ui.TextArea;
import com.vaadin.ui.TextField;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.declarative.Design;

import no.ssb.klass.designer.editing.components.EditLanguagesComponent;

/**
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed, e.g class LoginView extends LoginDesign
 * implements View { … }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class MetadataEditorComponentDesign extends VerticalLayout {
    protected VerticalLayout primaryLanguageLayout;
    protected Label primaryLanguageLabel;
    protected HorizontalLayout dateLayout;
    protected Label fromLabel;
    protected DateField fromDate;
    protected DateField toDate;
    protected CheckBox draftCheckBox;
    protected TextField primaryNameTextfield;
    protected TextArea primaryDescriptionTextArea;
    protected ComboBox contactPersonCombobox;
    protected TextField sectionTextfield;
    protected EditLanguagesComponent languageSelect;
    protected HorizontalLayout dateFillerLayout;
    protected HorizontalLayout draftFillerLayout;
    protected VerticalLayout secondLanguageLayout;
    protected TextField secondaryNameTextfield;
    protected TextArea secondaryDescriptionTextArea;
    protected VerticalLayout thirdLanguageLayout;
    protected TextField thirdNameTextfield;
    protected TextArea thirdDescriptionTextArea;

    public MetadataEditorComponentDesign() {
        Design.read(this);
    }
}
